[package]
name = "license-me"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
sysinfo = "0.26.3"
indicatif = "0.17.1"
log = "0.4.17"
env_logger = "0.9.1"
time = "0.3.14"